name: lumilivre
description: "Vitrine de livros da sua biblioteca."
publish_to: "none"
version: 1.0.0+1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-foreground.png"
  adaptive_icon_background: "#762075"
  adaptive_icon_foreground: "assets/images/logo-foreground.png"

flutter_native_splash:
  color: "#762075"
  color_dark: "#762075"
  image: assets/images/logo-foreground.png
  image_dark: assets/images/logo-foreground.png

  android_12:
    color: "#762075"
    color_dark: "#762075"
    image: assets/images/logo-foreground.png
    image_dark: assets/images/logo-foreground.png

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.1
  intl: ^0.20.2
  url_launcher: ^6.3.0
  local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
